import sequelize from '../config/database.js';
import Campaign from '../models/campaign.js';
import Lead from '../models/lead.js';
import LeadCampaign from '../models/leadCampaign.js';

const campaignsData = [
    {
        slug: 'campanha-super-vendas',
        title: 'Super Vendas',
        description: 'Aumente suas vendas com nossa campanha de incentivos.',
        status: true,
        available_at: new Date('2023-12-31'),
        user_id: 1,
        first_reward_title: 'Desconto de 10%',
        first_reward_text: 'Receba um desconto de 10% na sua próxima compra.',
        first_reward_video_url: 'http://example.com/video1',
        first_reward_how_it_works_title: 'Como funciona',
        first_reward_how_it_works_text: 'Indique amigos e ganhe recompensas.',
        first_reward_how_it_works_img_url: 'http://example.com/image1.jpg',
        second_reward_title: 'Desconto de 20%',
        second_reward_subtitle: 'Desconto para amigos',
        second_reward_text: 'Ganhe um desconto de 20% ao indicar 5 amigos.',
        second_reward_video_url: 'http://example.com/video2',
        second_reward_invite_title: 'Convide seus amigos',
        second_reward_invite_text: 'Convide amigos e ganhe mais descontos.',
        thanks_title: 'Obrigado por participar',
        thanks_text: 'Agradecemos sua participação.',
        first_reward_email_title: 'Parabéns! Você ganhou um desconto',
        first_reward_email_text: 'Use o código FIRST10 para ganhar 10% de desconto.',
        first_reward_email_link: 'http://example.com/first-reward',
        second_reward_email_title: 'Parabéns! Você ganhou mais descontos',
        second_reward_email_text: 'Use o código SECOND20 para ganhar 20% de desconto.',
        second_reward_email_link: 'http://example.com/second-reward',
        invite_email_title: 'Convide seus amigos e ganhe recompensas',
        invite_email_reward: 'Ganhe descontos incríveis ao indicar amigos.',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        slug: 'campanha-referral',
        title: 'Campanha Referral',
        description: 'Indique amigos e ganhe recompensas incríveis.',
        status: true,
        available_at: new Date('2023-12-31'),
        user_id: 1,
        first_reward_title: 'Desconto de 15%',
        first_reward_text: 'Receba um desconto de 15% na sua próxima compra.',
        first_reward_video_url: 'http://example.com/video3',
        first_reward_how_it_works_title: 'Como funciona',
        first_reward_how_it_works_text: 'Indique amigos e ganhe recompensas.',
        first_reward_how_it_works_img_url: 'http://example.com/image2.jpg',
        second_reward_title: 'Desconto de 25%',
        second_reward_subtitle: 'Desconto para amigos',
        second_reward_text: 'Ganhe um desconto de 25% ao indicar 5 amigos.',
        second_reward_video_url: 'http://example.com/video4',
        second_reward_invite_title: 'Convide seus amigos',
        second_reward_invite_text: 'Convide amigos e ganhe mais descontos.',
        thanks_title: 'Obrigado por participar',
        thanks_text: 'Agradecemos sua participação.',
        first_reward_email_title: 'Parabéns! Você ganhou um desconto',
        first_reward_email_text: 'Use o código REFERRAL15 para ganhar 15% de desconto.',
        first_reward_email_link: 'http://example.com/first-reward-referral',
        second_reward_email_title: 'Parabéns! Você ganhou mais descontos',
        second_reward_email_text: 'Use o código REFERRAL25 para ganhar 25% de desconto.',
        second_reward_email_link: 'http://example.com/second-reward-referral',
        invite_email_title: 'Convide seus amigos e ganhe recompensas',
        invite_email_reward: 'Ganhe descontos incríveis ao indicar amigos.',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        slug: 'campanha-premium',
        title: 'Campanha Premium',
        description: 'Ganhe recompensas exclusivas ao participar da nossa campanha.',
        status: true,
        available_at: new Date('2023-12-31'),
        user_id: 1,
        first_reward_title: 'Acesso VIP',
        first_reward_text: 'Receba um acesso VIP aos nossos produtos.',
        first_reward_video_url: 'http://example.com/video5',
        first_reward_how_it_works_title: 'Como funciona',
        first_reward_how_it_works_text: 'Indique amigos e ganhe recompensas.',
        first_reward_how_it_works_img_url: 'http://example.com/image3.jpg',
        second_reward_title: 'Desconto de 30%',
        second_reward_subtitle: 'Desconto para amigos',
        second_reward_text: 'Ganhe um desconto de 30% ao indicar 5 amigos.',
        second_reward_video_url: 'http://example.com/video6',
        second_reward_invite_title: 'Convide seus amigos',
        second_reward_invite_text: 'Convide amigos e ganhe mais descontos.',
        thanks_title: 'Obrigado por participar',
        thanks_text: 'Agradecemos sua participação.',
        first_reward_email_title: 'Parabéns! Você ganhou um acesso VIP',
        first_reward_email_text: 'Use o código VIPACCESS para ganhar acesso VIP.',
        first_reward_email_link: 'http://example.com/first-reward-premium',
        second_reward_email_title: 'Parabéns! Você ganhou mais descontos',
        second_reward_email_text: 'Use o código PREMIUM30 para ganhar 30% de desconto.',
        second_reward_email_link: 'http://example.com/second-reward-premium',
        invite_email_title: 'Convide seus amigos e ganhe recompensas',
        invite_email_reward: 'Ganhe descontos incríveis ao indicar amigos.',
        created_at: new Date(),
        updated_at: new Date(),
    },
];

const leadsData = [
  {
      name: 'João Silva',
      email: 'joao.silva@example.com',
      whatsapp: '11999999999',
      created_at: new Date(),
      updated_at: new Date(),
  },
  {
      name: 'Maria Oliveira',
      email: 'maria.oliveira@example.com',
      whatsapp: '21999999999',
      created_at: new Date(),
      updated_at: new Date(),
  },
  {
      name: 'Carlos Souza',
      email: 'carlos.souza@example.com',
      whatsapp: '31999999999',
      created_at: new Date(),
      updated_at: new Date(),
  },
  {
      name: 'Ana Pereira',
      email: 'ana.pereira@example.com',
      whatsapp: '41999999999',
      created_at: new Date(),
      updated_at: new Date(),
  },
  {
      name: 'Pedro Costa',
      email: 'pedro.costa@example.com',
      whatsapp: '51999999999',
      created_at: new Date(),
      updated_at: new Date(),
  },
  {
      name: 'Fernanda Lima',
      email: 'fernanda.lima@example.com',
      whatsapp: '61999999999',
      created_at: new Date(),
      updated_at: new Date(),
  },
  {
      name: 'Rafael Almeida',
      email: 'rafael.almeida@example.com',
      whatsapp: '71999999999',
      created_at: new Date(),
      updated_at: new Date(),
  },
  {
      name: 'Juliana Barbosa',
      email: 'juliana.barbosa@example.com',
      whatsapp: '81999999999',
      created_at: new Date(),
      updated_at: new Date(),
  },
  {
      name: 'Rodrigo Martins',
      email: 'rodrigo.martins@example.com',
      whatsapp: '91999999999',
      created_at: new Date(),
      updated_at: new Date(),
  },
  {
      name: 'Camila Souza',
      email: 'camila.souza@example.com',
      whatsapp: '10199999999',
      created_at: new Date(),
      updated_at: new Date(),
  },
  {
      name: 'Bruno Ferreira',
      email: 'bruno.ferreira@example.com',
      whatsapp: '11199999999',
      created_at: new Date(),
      updated_at: new Date(),
  },
  {
      name: 'Laura Rodrigues',
      email: 'laura.rodrigues@example.com',
      whatsapp: '12199999999',
      created_at: new Date(),
      updated_at: new Date(),
  },
  {
      name: 'Gustavo Santos',
      email: 'gustavo.santos@example.com',
      whatsapp: '13199999999',
      created_at: new Date(),
      updated_at: new Date(),
  },
  {
      name: 'Patricia Ribeiro',
      email: 'patricia.ribeiro@example.com',
      whatsapp: '14199999999',
      created_at: new Date(),
      updated_at: new Date(),
  },
  {
      name: 'Felipe Mendes',
      email: 'felipe.mendes@example.com',
      whatsapp: '15199999999',
      created_at: new Date(),
      updated_at: new Date(),
  },
  {
      name: 'Renata Campos',
      email: 'renata.campos@example.com',
      whatsapp: '16199999999',
      created_at: new Date(),
      updated_at: new Date(),
  },
  {
      name: 'Vinicius Araujo',
      email: 'vinicius.araujo@example.com',
      whatsapp: '17199999999',
      created_at: new Date(),
      updated_at: new Date(),
  },
  {
      name: 'Tatiana Oliveira',
      email: 'tatiana.oliveira@example.com',
      whatsapp: '18199999999',
      created_at: new Date(),
      updated_at: new Date(),
  },
  {
      name: 'Leonardo Ferreira',
      email: 'leonardo.ferreira@example.com',
      whatsapp: '19199999999',
      created_at: new Date(),
      updated_at: new Date(),
  },
  {
      name: 'Sofia Lopes',
      email: 'sofia.lopes@example.com',
      whatsapp: '20199999999',
      created_at: new Date(),
      updated_at: new Date(),
  },
  {
      name: 'André Dias',
      email: 'andre.dias@example.com',
      whatsapp: '21199999999',
      created_at: new Date(),
      updated_at: new Date(),
  },
  {
      name: 'Gabriela Nunes',
      email: 'gabriela.nunes@example.com',
      whatsapp: '22199999999',
      created_at: new Date(),
      updated_at: new Date(),
  },
  {
      name: 'Ricardo Fernandes',
      email: 'ricardo.fernandes@example.com',
      whatsapp: '23199999999',
      created_at: new Date(),
      updated_at: new Date(),
  },
  {
      name: 'Marta Carvalho',
      email: 'marta.carvalho@example.com',
      whatsapp: '24199999999',
      created_at: new Date(),
      updated_at: new Date(),
  },
  {
      name: 'Thiago Gomes',
      email: 'thiago.gomes@example.com',
      whatsapp: '25199999999',
      created_at: new Date(),
      updated_at: new Date(),
  },
  {
      name: 'Amanda Rocha',
      email: 'amanda.rocha@example.com',
      whatsapp: '26199999999',
      created_at: new Date(),
      updated_at: new Date(),
  },
  {
      name: 'Eduardo Vieira',
      email: 'eduardo.vieira@example.com',
      whatsapp: '27199999999',
      created_at: new Date(),
      updated_at: new Date(),
  },
  {
      name: 'Beatriz Souza',
      email: 'beatriz.souza@example.com',
      whatsapp: '28199999999',
      created_at: new Date(),
      updated_at: new Date(),
  },
  {
      name: 'Diego Almeida',
      email: 'diego.almeida@example.com',
      whatsapp: '29199999999',
      created_at: new Date(),
      updated_at: new Date(),
  },
  {
      name: 'Elaine Mendes',
      email: 'elaine.mendes@example.com',
      whatsapp: '30199999999',
      created_at: new Date(),
      updated_at: new Date(),
  },
];

const leadCampaignsData = [];

for (let i = 0; i < leadsData.length; i++) {
    leadCampaignsData.push({
        user_id: 1,
        campaign_id: Math.floor(Math.random() * 3) + 1,
        lead_id: i + 1,
        invited_by_lead_id: i > 0 ? Math.floor(Math.random() * i) + 1 : null,
        accept_invite: Math.random() > 0.5,
        accepted_at: new Date(),
        created_at: new Date(),
        updated_at: new Date(),
    });
}

const populateDatabase = async () => {
    try {
        await sequelize.sync({ alter: true });

        await Campaign.bulkCreate(campaignsData);
        await Lead.bulkCreate(leadsData);
        await LeadCampaign.bulkCreate(leadCampaignsData);

        console.log('Banco de dados populado com sucesso!');
    } catch (error) {
        console.error('Erro ao popular o banco de dados:', error);
    } finally {
        await sequelize.close();
    }
};

populateDatabase();
